---
title: "earthquake forecasting setup"
author: "Saksham Joshi"
date: "2023-07-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
install.packages("systemfonts")
install.packages("textshaping")
install.packages("ragg")
install.packages("tidyverse")
install.packages("tidyquant")
install.packages("lemon")
install.packages("ggpubr")
install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
install.packages("ggspatial")
```

```{r warning=FALSE}
library(ETAS.inlabru)

library(tidyquant)
library(gridExtra)
library(grid)
library(lemon)
library(ggplot2)
library(ggpubr)
library(GGally)

library(inlabru)
library(INLA)
library(ETAS.inlabru)

# inla.setOption(pardiso.license="~/sys/licences/pardiso.lic")

library(dplyr)

# Increase num.threads if you have more cores on your computer
INLA::inla.setOption(num.threads = 2)
```

```{r}
library(ETAS.inlabru)
library(ggplot2)

library(rnaturalearth)
library(terra)
library(sf)
library(ggspatial)
library(rnaturalearthdata)
library(dplyr)
library(lubridate)

## This is just the EPSG equivalent of WGS84
crs_wgs84 <- st_crs('EPSG:4326')
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
